# Generated by Django 2.2 on 2019-12-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_auto_20191213_1436'),
        ('physicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinical_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'telorder'), (2, 'visit'), (2, 'tele-medecine')])),
                ('description', models.TextField()),
                ('data', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(null=True, on_delete=True, to='patient.Patient')),
                ('physician_id', models.ForeignKey(null=True, on_delete=True, to='physicing.physician')),
            ],
        ),
        migrations.CreateModel(
            name='treatment_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('description', models.TextField()),
                ('Clinical_record_id', models.ForeignKey(null=True, on_delete=True, to='clinical.Clinical_record')),
                ('patient_id', models.ForeignKey(null=True, on_delete=True, to='patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='medecine_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=150)),
                ('qty', models.IntegerField()),
                ('description', models.TextField()),
                ('Clinical_record_id', models.ForeignKey(null=True, on_delete=True, to='clinical.Clinical_record')),
                ('patient_id', models.ForeignKey(null=True, on_delete=True, to='patient.Patient')),
            ],
        ),
    ]
