# Generated by Django 2.2 on 2019-12-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_record',
            name='category',
            field=models.IntegerField(choices=[(1, 'telorder'), (2, 'visit'), (3, 'tele-medecine')]),
        ),
    ]
