# Generated by Django 2.2 on 2019-12-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_auto_20191213_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_record',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=True, related_name='clinical_record', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='medecine_order',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=True, related_name='medecine_order', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='treatment_order',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=True, related_name='treatment_order', to='patient.Patient'),
        ),
    ]
