# Generated by Django 2.2 on 2019-12-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_auto_20191221_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_record',
            name='physician_id',
            field=models.ForeignKey(null=True, on_delete=True, related_name='clinical_record', to='physicing.physician'),
        ),
        migrations.AlterField(
            model_name='medecine_order',
            name='Clinical_record_id',
            field=models.ForeignKey(null=True, on_delete=True, related_name='medecine_order', to='clinical.Clinical_record'),
        ),
        migrations.AlterField(
            model_name='treatment_order',
            name='Clinical_record_id',
            field=models.ForeignKey(null=True, on_delete=True, related_name='treatment_order', to='clinical.Clinical_record'),
        ),
    ]
