# Generated by Django 2.2 on 2019-12-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParaClininical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_record',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=True, related_name='operation_record', to='patient.Patient'),
        ),
    ]
