# Generated by Django 2.2 on 2019-12-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'laser'), (2, 'disk'), (3, 'RF'), (4, 'epidoroscopy'), (5, 'endoscopy')])),
            ],
        ),
    ]
