# Generated by Django 2.2 on 2019-12-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('national_code', models.CharField(max_length=15)),
                ('birthday', models.DateTimeField(auto_now=True)),
                ('gender', models.IntegerField(choices=[(1, 'men'), (2, 'women')])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Refrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('patient_id', models.ForeignKey(null=True, on_delete=True, to='patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior')], max_length=160)),
                ('value', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(null=True, on_delete=True, to='patient.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kay', models.IntegerField(choices=[(1, 'adress'), (2, 'email'), (3, 'phone')])),
                ('value', models.TextField()),
                ('patient_id', models.ForeignKey(null=True, on_delete=True, to='patient.Patient')),
            ],
        ),
    ]
