# Generated by Django 2.2 on 2019-12-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20191213_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AlterField(
            model_name='contact',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='record',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=True, related_name='record', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='refrence',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=True, related_name='refrence', to='patient.Patient'),
        ),
    ]
